name: WaniKani

options:
  bundleIdPrefix: com.angansamadder
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15.0"

configs:
  Debug: debug
  Release: release

targets:
  WaniKaniWebView:
    type: application
    platform: iOS
    sources:
      - WaniKani
    dependencies:
      - target: WaniKaniCore
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.angansamadder.wanikani.webview
        INFOPLIST_GENERATION_MODE: GeneratedFile
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_UISupportedInterfaceOrientations: [UIInterfaceOrientationPortrait, UIInterfaceOrientationPortraitUpsideDown, UIInterfaceOrientationLandscapeLeft, UIInterfaceOrientationLandscapeRight]
        MARKETING_VERSION: "1.0"
        CURRENT_PROJECT_VERSION: "1"
        SWIFT_EMIT_LOC_STRINGS: YES
        STRING_CATALOG_GENERATE_SYMBOLS: YES
        ASSETCATALOG_COMPILER_GENERATE_SWIFT_ASSET_SYMBOL_EXTENSIONS: YES
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        ENABLE_PREVIEWS: YES
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: "39YTAJZTZ6"
        ENABLE_USER_SCRIPT_SANDBOXING: YES

  WaniKaniNative:
    type: application
    platform: iOS
    sources:
      - WaniKani
    dependencies:
      - target: WaniKaniCore
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.angansamadder.wanikani.native
        INFOPLIST_GENERATION_MODE: GeneratedFile
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_UISupportedInterfaceOrientations: [UIInterfaceOrientationPortrait, UIInterfaceOrientationPortraitUpsideDown, UIInterfaceOrientationLandscapeLeft, UIInterfaceOrientationLandscapeRight]
        MARKETING_VERSION: "1.0"
        CURRENT_PROJECT_VERSION: "1"
        SWIFT_EMIT_LOC_STRINGS: YES
        STRING_CATALOG_GENERATE_SYMBOLS: YES
        ASSETCATALOG_COMPILER_GENERATE_SWIFT_ASSET_SYMBOL_EXTENSIONS: YES
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        ENABLE_PREVIEWS: YES
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: "39YTAJZTZ6"
        ENABLE_USER_SCRIPT_SANDBOXING: YES

  WaniKaniHybrid:
    type: application
    platform: iOS
    sources:
      - WaniKani
    dependencies:
      - target: WaniKaniCore
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.angansamadder.wanikani.hybrid
        INFOPLIST_GENERATION_MODE: GeneratedFile
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_UISupportedInterfaceOrientations: [UIInterfaceOrientationPortrait, UIInterfaceOrientationPortraitUpsideDown, UIInterfaceOrientationLandscapeLeft, UIInterfaceOrientationLandscapeRight]
        MARKETING_VERSION: "1.0"
        CURRENT_PROJECT_VERSION: "1"
        SWIFT_EMIT_LOC_STRINGS: YES
        STRING_CATALOG_GENERATE_SYMBOLS: YES
        ASSETCATALOG_COMPILER_GENERATE_SWIFT_ASSET_SYMBOL_EXTENSIONS: YES
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        ENABLE_PREVIEWS: YES
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: "39YTAJZTZ6"
        ENABLE_USER_SCRIPT_SANDBOXING: YES

  WaniKaniCore:
    type: framework
    platform: iOS
    sources:
      - WaniKaniCore
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.angansamadder.wanikani.core
        INFOPLIST_GENERATION_MODE: GeneratedFile
        GENERATE_INFOPLIST_FILE: YES
        MARKETING_VERSION: "1.0"
        CURRENT_PROJECT_VERSION: "1"
        SKIP_INSTALL: YES
        DEFINES_MODULE: YES
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: "39YTAJZTZ6"
        ENABLE_MODULE_VERIFIER: YES
        ENABLE_USER_SCRIPT_SANDBOXING: YES

  WaniKaniTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - WaniKaniTests
    dependencies:
      - target: WaniKaniNative # Default to native for testing host
      - target: WaniKaniCore
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.angansamadder.wanikani.tests
        INFOPLIST_GENERATION_MODE: GeneratedFile
        GENERATE_INFOPLIST_FILE: YES
        TEST_HOST: "$(BUILT_PRODUCTS_DIR)/WaniKaniNative.app/$(BUNDLE_EXECUTABLE_FOLDER_PATH)/WaniKaniNative"
        BUNDLE_LOADER: "$(TEST_HOST)"
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: "39YTAJZTZ6"

  WaniKaniUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - WaniKaniUITests
    dependencies:
      - target: WaniKaniNative
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.angansamadder.wanikani.uitests
        INFOPLIST_GENERATION_MODE: GeneratedFile
        GENERATE_INFOPLIST_FILE: YES
        TEST_TARGET_NAME: WaniKaniNative
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: "39YTAJZTZ6"

schemes:
  WaniKani-WebView:
    build:
      targets:
        WaniKaniWebView: all
        WaniKaniCore: [run, test]
    run:
      config: Debug
      environmentVariables:
        - variable: PROTOTYPE_MODE
          value: webview
          isEnabled: true
    test:
      config: Debug
      gatherCoverageData: true
      targets:
        - WaniKaniTests
        - WaniKaniUITests
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release

  WaniKani-Native:
    build:
      targets:
        WaniKaniNative: all
        WaniKaniCore: [run, test]
    run:
      config: Debug
      environmentVariables:
        - variable: PROTOTYPE_MODE
          value: native
          isEnabled: true
    test:
      config: Debug
      gatherCoverageData: true
      targets:
        - WaniKaniTests
        - WaniKaniUITests
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release

  WaniKani-Hybrid:
    build:
      targets:
        WaniKaniHybrid: all
        WaniKaniCore: [run, test]
    run:
      config: Debug
      environmentVariables:
        - variable: PROTOTYPE_MODE
          value: hybrid
          isEnabled: true
    test:
      config: Debug
      gatherCoverageData: true
      targets:
        - WaniKaniTests
        - WaniKaniUITests
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
