import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";

type Tokens = {
  color: Record<string, string>;
  spacing: Record<string, number>;
  radius: Record<string, number>;
};

const checkOnly = process.argv.includes("--check");
const packageRoot = process.cwd();
const repoRoot = resolve(packageRoot, "../..");
const tokensPath = resolve(packageRoot, "src/tokens.json");
const distDir = resolve(packageRoot, "dist");
const iosGeneratedPath = resolve(
  repoRoot,
  "apps/ios/WaniKani/Shared/Theme/WKDesignTokens+Generated.swift"
);
const androidGeneratedPath = resolve(
  repoRoot,
  "apps/android/app/src/main/kotlin/com/angansamadder/wanikani/android/tokens/WkTokensGenerated.kt"
);
const distSwiftPath = resolve(distDir, "WKDesignTokens+Generated.swift");
const distKotlinPath = resolve(distDir, "WkTokensGenerated.kt");

const tokens = JSON.parse(readFileSync(tokensPath, "utf8")) as Tokens;

function sanitizeSwiftIdentifier(input: string): string {
  const parts = input
    .replace(/[^a-zA-Z0-9]+/g, " ")
    .trim()
    .split(/\s+/)
    .filter(Boolean);

  return parts
    .map((part, index) => {
      if (index === 0) {
        return part.charAt(0).toLowerCase() + part.slice(1);
      }
      return part.charAt(0).toUpperCase() + part.slice(1);
    })
    .join("");
}

function sanitizeKotlinIdentifier(input: string): string {
  return input
    .replace(/[^a-zA-Z0-9]+/g, "_")
    .replace(/^_+|_+$/g, "")
    .toUpperCase();
}

function hexToRGB(hex: string): { r: number; g: number; b: number } {
  const normalized = hex.replace("#", "");
  const value = Number.parseInt(normalized, 16);
  return {
    r: (value >> 16) & 0xff,
    g: (value >> 8) & 0xff,
    b: value & 0xff
  };
}

const swiftColors = Object.entries(tokens.color)
  .map(([name, hex]) => {
    const { r, g, b } = hexToRGB(hex);
    return `    public static let ${sanitizeSwiftIdentifier(name)} = Color(red: ${(r / 255).toFixed(4)}, green: ${(g / 255).toFixed(4)}, blue: ${(b / 255).toFixed(4)})`;
  })
  .join("\n");

const swiftSpacing = Object.entries(tokens.spacing)
  .map(([name, value]) => `    public static let ${sanitizeSwiftIdentifier(name)}: CGFloat = ${value}`)
  .join("\n");

const swiftRadius = Object.entries(tokens.radius)
  .map(([name, value]) => `    public static let ${sanitizeSwiftIdentifier(name)}: CGFloat = ${value}`)
  .join("\n");

const swiftFile = `import SwiftUI\n\n// Generated by packages/design-tokens/scripts/build.ts\npublic enum WKDesignTokens {\n${swiftColors}\n\n    public enum Spacing {\n${swiftSpacing}\n    }\n\n    public enum Radius {\n${swiftRadius}\n    }\n}\n`;

const kotlinColors = Object.entries(tokens.color)
  .map(([name, hex]) => `    const val ${sanitizeKotlinIdentifier(name)} = \"${hex}\"`)
  .join("\n");

const kotlinSpacing = Object.entries(tokens.spacing)
  .map(([name, value]) => `    const val ${sanitizeKotlinIdentifier(name)} = ${value}`)
  .join("\n");

const kotlinRadius = Object.entries(tokens.radius)
  .map(([name, value]) => `    const val ${sanitizeKotlinIdentifier(name)} = ${value}`)
  .join("\n");

const kotlinFile = `package com.angansamadder.wanikani.android.tokens\n\n// Generated by packages/design-tokens/scripts/build.ts\nobject WkTokensGenerated {\n${kotlinColors}\n\n    object Spacing {\n${kotlinSpacing}\n    }\n\n    object Radius {\n${kotlinRadius}\n    }\n}\n`;

if (!checkOnly) {
  mkdirSync(distDir, { recursive: true });
  mkdirSync(dirname(iosGeneratedPath), { recursive: true });
  mkdirSync(dirname(androidGeneratedPath), { recursive: true });

  writeFileSync(distSwiftPath, swiftFile);
  writeFileSync(distKotlinPath, kotlinFile);
  writeFileSync(iosGeneratedPath, swiftFile);
  writeFileSync(androidGeneratedPath, kotlinFile);

  console.log("Generated token artifacts:");
  console.log(`- ${distSwiftPath}`);
  console.log(`- ${distKotlinPath}`);
  console.log(`- ${iosGeneratedPath}`);
  console.log(`- ${androidGeneratedPath}`);
} else {
  console.log("Token generation script check completed.");
}
